GET http://localhost:5000

###

POST http://localhost:5000
Content-Type: application/json
Accept: application/json

{
    "todo": "Belajar JS"
}

###
PUT http://localhost:5000
Content-Type: application/json
Accept: application/json

{
    "id": 0,
    "todo": "Belajar Node JS"
}

###

DELETE http://localhost:5000
Content-Type: application/json
Accept: application/json

{
    "id": 0
}